
-- Journal table
CREATE TABLE students_audit_table (
                                      audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                      action_type VARCHAR2(20),
                                      student_id NUMBER,
                                      student_name VARCHAR2(100),
                                      group_id NUMBER,
                                      action_date TIMESTAMP DEFAULT SYSTIMESTAMP,
                                      CONSTRAINT pk_audit_id PRIMARY KEY (audit_id)
);


-- Logging trigger
create or replace TRIGGER students_audit_trigger
    AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN
        v_action := 'INSERT';
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
    ELSE
        v_action := 'DELETE';
    END IF;

    INSERT INTO students_audit_table (action_type, student_id, student_name, group_id, action_date)
    VALUES (v_action, :NEW.ID, :NEW.NAME, :NEW.GROUP_ID, SYSTIMESTAMP);
END;