CREATE TABLE students_audit_table_tmp (
                                          audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                          action_type VARCHAR2(20),
                                          student_id NUMBER,
                                          student_name VARCHAR2(100),
                                          group_id NUMBER,
                                          old_student_name VARCHAR2(100),
                                          old_group_id NUMBER,
                                          action_date TIMESTAMP DEFAULT SYSTIMESTAMP,
                                          CONSTRAINT pk_audit_id_tmp PRIMARY KEY (audit_id)
);

INSERT INTO students_audit_table_tmp (audit_id, action_type, student_id, student_name, group_id, old_student_name, old_group_id, action_date)
SELECT audit_id, action_type, student_id, student_name, group_id, NULL AS old_student_name, NULL AS old_group_id, action_date
FROM students_audit_table;

DROP TABLE students_audit_table;

ALTER TABLE students_audit_table_tmp RENAME TO students_audit_table;
